# Generated by Django 4.0.4 on 2022-05-10 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squishmallow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('squish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('3.5', '3.5" Clip On'), ('5', '5"'), ('6', '6"'), ('7', '7"'), ('7.5', '7.5"'), ('8', '8"'), ('10', '10"'), ('12', '12"'), ('14', '14"'), ('16', '16"'), ('20', '20"'), ('24', '24"'), ('H', 'Hug Mee'), ('S', 'Stackable'), ('F', 'Flip-A-Mallow')], max_length=4)),
                ('squishmallow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.squishmallow')),
            ],
        ),
    ]
