# Generated by Django 4.0.4 on 2022-05-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_squishmallow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='squishmallow',
            name='size',
            field=models.CharField(choices=[('3.5', '3.5" Clip On'), ('5', '5"'), ('6', '6"'), ('7', '7"'), ('7.5', '7.5"'), ('8', '8"'), ('10', '10"'), ('12', '12"'), ('14', '14"'), ('16', '16"'), ('20', '20"'), ('24', '24"'), ('H', 'Hug Mee'), ('S', 'Stackable'), ('F', 'Flip-A-Mallow')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
