# Generated by Django 4.0.4 on 2022-05-21 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_squishmallow_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squishmallow',
            old_name='squish_date',
            new_name='date_acquired',
        ),
    ]
